# Generated by Django 4.0 on 2022-01-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('acc_holder_name', models.CharField(max_length=30)),
                ('acc_no', models.CharField(max_length=30)),
                ('initial_balance', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('credit_balance', models.FloatField(null=True)),
                ('debit_balance', models.FloatField(null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'bank_account_master',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=30)),
                ('ar_name', models.CharField(max_length=30)),
                ('en_place', models.CharField(max_length=30)),
                ('ar_place', models.CharField(max_length=30)),
                ('en_district', models.CharField(max_length=30)),
                ('ar_district', models.CharField(max_length=30)),
                ('vat_no', models.CharField(max_length=15)),
                ('lan_no', models.CharField(max_length=15)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[('1', 'customer'), ('2', 'supplier')], default='1', max_length=15)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance_bank', models.FloatField(null=True)),
                ('cash_opening_balance', models.FloatField(null=True)),
                ('closing_balance_bank', models.FloatField(null=True)),
                ('closing_balance_cash', models.FloatField(null=True)),
                ('total_transactions', models.FloatField(null=True)),
                ('total_sales', models.FloatField(null=True)),
                ('total_purchase', models.FloatField(null=True)),
                ('total_expense', models.FloatField(null=True)),
                ('total_cash_sales', models.FloatField(null=True)),
                ('total_cash_purchase', models.FloatField(null=True)),
                ('total_bank_purchase', models.FloatField(null=True)),
                ('total_bank_sales', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bankaccountmaster')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'daily_session_master',
            },
        ),
        migrations.CreateModel(
            name='Dispence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'dispence',
            },
        ),
        migrations.CreateModel(
            name='FuelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fuel_vat', models.IntegerField()),
                ('rate', models.FloatField(null=True)),
                ('payable_amt', models.FloatField(null=True)),
                ('current_stock', models.FloatField(null=True)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'fuel_master',
            },
        ),
        migrations.CreateModel(
            name='VatMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.FloatField()),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'vat_master',
            },
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref_no', models.CharField(max_length=30)),
                ('paid_amt', models.FloatField()),
                ('paid_type', models.CharField(max_length=30)),
                ('total_amt', models.FloatField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bankaccountmaster', verbose_name='bank')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'payment_out',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_reading', models.FloatField()),
                ('end_reading', models.FloatField()),
                ('payable_amt', models.FloatField()),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_company', to='administrator.company')),
                ('dispence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.dispence')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.employee')),
            ],
            options={
                'db_table': 'meter_reading',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.FloatField()),
                ('gross_amt', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('1', 'CASH'), ('2', 'BANK'), ('3', 'CREDIT')], default='1', max_length=15)),
                ('type', models.CharField(choices=[('1', 'in_invoice'), ('2', 'out_invoice'), ('3', 'expense')], default='1', max_length=15)),
                ('total_amt', models.FloatField(blank=True, null=True)),
                ('credit_amount', models.FloatField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vat_percenatge', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('paid_amt', models.FloatField(blank=True, default=0, null=True)),
                ('balance_amt', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exp_type', models.CharField(blank=True, max_length=30, null=True)),
                ('fuelvat_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bankaccountmaster')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.contact', verbose_name='contact')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.employee', verbose_name='employee')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.fuelmaster', verbose_name='fuel')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.dailysession')),
                ('vat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.vatmaster')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='FuelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(null=True)),
                ('Fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.fuelmaster')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'fuel_quantity',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exp_type', models.CharField(max_length=30)),
                ('ref_no', models.CharField(max_length=30)),
                ('paid_amt', models.FloatField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bankaccountmaster', verbose_name='bank')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.owner')),
            ],
            options={
                'db_table': 'deposit',
            },
        ),
        migrations.CreateModel(
            name='CashMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('cash_ac_name', models.CharField(max_length=30, null=True)),
                ('credit_balance', models.FloatField(null=True)),
                ('debit_balance', models.FloatField(null=True)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.owner')),
            ],
            options={
                'db_table': 'cash_master',
            },
        ),
        migrations.AddField(
            model_name='bankaccountmaster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.owner'),
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(null=True)),
                ('debit_balance', models.FloatField(null=True)),
                ('credit_balance', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.bankaccountmaster')),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.branches')),
                ('cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.cashmaster')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.company')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.dailysession')),
            ],
            options={
                'db_table': 'Daily_Account_Ledger',
            },
        ),
    ]
