# Generated by Django 4.0 on 2022-01-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_accountledger_total_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.cashmaster'),
        ),
    ]
