# Generated by Django 4.0 on 2022-01-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('company', '0004_invoice_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='bankaccountmaster',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='cashmaster',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='dispence',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='fuelmaster',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='fuelstock',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
        migrations.AlterField(
            model_name='vatmaster',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.branches'),
        ),
    ]
