# Generated by Django 4.0 on 2022-01-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_deposit_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelmaster',
            name='branches',
        ),
    ]
