# Generated by Django 4.0 on 2022-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_fuelmaster_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
