# Generated by Django 4.0 on 2022-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_cashmaster_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ref_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
