# Generated by Django 4.0 on 2022-02-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_invoice_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.fuelmaster', verbose_name='fuel'),
        ),
    ]
