# Generated by Django 4.0 on 2022-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_meterreading_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='fuel_stock',
            field=models.FloatField(null=True),
        ),
    ]
