# Generated by Django 4.0 on 2022-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_meterreading_fuel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='fuel_stock',
            field=models.FloatField(default=0, null=True),
        ),
    ]
