# Generated by Django 4.0 on 2022-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_dispence_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='base_64_encoded',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
