# Generated by Django 4.0 on 2022-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(unique=True)),
                ('expiry', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'otp_expiry',
            },
        ),
    ]
