# Generated by Django 4.0 on 2022-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_otpexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpexpiry',
            name='current_time',
            field=models.TimeField(null=True),
        ),
    ]
