# Generated by Django 4.0 on 2022-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_otpexpiry_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
