# Generated by Django 4.0 on 2022-02-12 14:50

import administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_profileimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=administrator.models.get_upload_path, verbose_name='logo'),
        ),
    ]
